# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Apr 25 23:05:54 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1521, 730)
        self.centralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 0, 1471, 701))
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.logText = QtGui.QPlainTextEdit(self.widget)
        self.logText.setGeometry(QtCore.QRect(1040, 400, 411, 211))
        self.logText.setObjectName("logText")
        self.mapView = QtGui.QGraphicsView(self.widget)
        self.mapView.setGeometry(QtCore.QRect(0, 0, 1001, 611))
        self.mapView.setProperty("cursor", QtCore.Qt.CrossCursor)
        self.mapView.setMouseTracking(True)
        self.mapView.setObjectName("mapView")
        self.label = QtGui.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(12, 2, 61, 16))
        self.label.setObjectName("label")
        self.layoutWidget = QtGui.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(1170, 10, 240, 152))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(100, 40))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.regionName = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regionName.sizePolicy().hasHeightForWidth())
        self.regionName.setSizePolicy(sizePolicy)
        self.regionName.setMaximumSize(QtCore.QSize(200, 40))
        self.regionName.setObjectName("regionName")
        self.horizontalLayout.addWidget(self.regionName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.beginButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beginButton.sizePolicy().hasHeightForWidth())
        self.beginButton.setSizePolicy(sizePolicy)
        self.beginButton.setObjectName("beginButton")
        self.horizontalLayout_2.addWidget(self.beginButton)
        self.endButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endButton.sizePolicy().hasHeightForWidth())
        self.endButton.setSizePolicy(sizePolicy)
        self.endButton.setObjectName("endButton")
        self.horizontalLayout_2.addWidget(self.endButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.clearButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setMinimumSize(QtCore.QSize(100, 0))
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_3.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.linkButton = QtGui.QPushButton(self.layoutWidget)
        self.linkButton.setObjectName("linkButton")
        self.horizontalLayout_4.addWidget(self.linkButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.regionList = QtGui.QListWidget(self.widget)
        self.regionList.setGeometry(QtCore.QRect(1040, 180, 411, 191))
        self.regionList.setObjectName("regionList")
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.mapView_2 = QtGui.QGraphicsView(self.tab_2)
        self.mapView_2.setGeometry(QtCore.QRect(0, 0, 1001, 611))
        self.mapView_2.setProperty("cursor", QtCore.Qt.CrossCursor)
        self.mapView_2.setMouseTracking(True)
        self.mapView_2.setObjectName("mapView_2")
        self.logText_2 = QtGui.QPlainTextEdit(self.tab_2)
        self.logText_2.setGeometry(QtCore.QRect(1020, 300, 411, 211))
        self.logText_2.setObjectName("logText_2")
        self.widget1 = QtGui.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(1130, 50, 151, 128))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.startLinkButton = QtGui.QPushButton(self.widget1)
        self.startLinkButton.setObjectName("startLinkButton")
        self.verticalLayout_2.addWidget(self.startLinkButton)
        self.endLinkButton = QtGui.QPushButton(self.widget1)
        self.endLinkButton.setObjectName("endLinkButton")
        self.verticalLayout_2.addWidget(self.endLinkButton)
        self.startRemoveButton = QtGui.QPushButton(self.widget1)
        self.startRemoveButton.setObjectName("startRemoveButton")
        self.verticalLayout_2.addWidget(self.startRemoveButton)
        self.endRemoveButton = QtGui.QPushButton(self.widget1)
        self.endRemoveButton.setObjectName("endRemoveButton")
        self.verticalLayout_2.addWidget(self.endRemoveButton)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1521, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.beginButton, QtCore.SIGNAL("clicked()"), MainWindow.beginRegion)
        QtCore.QObject.connect(self.endButton, QtCore.SIGNAL("clicked()"), MainWindow.endRegion)
        QtCore.QObject.connect(self.clearButton, QtCore.SIGNAL("clicked()"), MainWindow.clearRegion)
        QtCore.QObject.connect(self.actionOpen, QtCore.SIGNAL("triggered()"), MainWindow.actionOpen)
        QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL("triggered()"), MainWindow.actionSave)
        QtCore.QObject.connect(self.linkButton, QtCore.SIGNAL("clicked()"), MainWindow.link)
        QtCore.QObject.connect(self.tabWidget, QtCore.SIGNAL("currentChanged(int)"), MainWindow.tabChange)
        QtCore.QObject.connect(self.startLinkButton, QtCore.SIGNAL("clicked()"), MainWindow.startLinking)
        QtCore.QObject.connect(self.endLinkButton, QtCore.SIGNAL("clicked()"), MainWindow.endLinking)
        QtCore.QObject.connect(self.startRemoveButton, QtCore.SIGNAL("clicked()"), MainWindow.startRemoving)
        QtCore.QObject.connect(self.endRemoveButton, QtCore.SIGNAL("clicked()"), MainWindow.endRemoving)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Map View", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "RegionName", None, QtGui.QApplication.UnicodeUTF8))
        self.beginButton.setText(QtGui.QApplication.translate("MainWindow", "Begin Area", None, QtGui.QApplication.UnicodeUTF8))
        self.endButton.setText(QtGui.QApplication.translate("MainWindow", "End Area", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.linkButton.setText(QtGui.QApplication.translate("MainWindow", "Link", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.startLinkButton.setText(QtGui.QApplication.translate("MainWindow", "Start Linking", None, QtGui.QApplication.UnicodeUTF8))
        self.endLinkButton.setText(QtGui.QApplication.translate("MainWindow", "End Linking", None, QtGui.QApplication.UnicodeUTF8))
        self.startRemoveButton.setText(QtGui.QApplication.translate("MainWindow", "Start Removing", None, QtGui.QApplication.UnicodeUTF8))
        self.endRemoveButton.setText(QtGui.QApplication.translate("MainWindow", "End Removing", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))

